### ISSUE TITLE
Access initial headers in Meteor.onConnect callback

### ISSUE THREAD

**Issue by hyperborea** [gadicc/meteor-headers#30]
How do you access (initial) server headers directly and exclusively on the server? From what I understand headers.get() is only available within Meteor.methods and Meteor.publish, but I don't actually want to expose it to the client. I was hoping I could catch them on Meteor.onConnection(), but that doesn't seem to be possible. Could you please give a short example how I can access header information on the server whenever a client initially connects to Meteor?

To explain, I'd like to implement a simple SSO login within a company network using header information.

**Comment by djlogan2** [comment]
I'm running into the same problem. Users login using a different method, and I just get the http headers. I am hoping to keep track of when users connect to and disconnect from the server so I can join them and leave them from tournaments if they close the pages, so I was hoping to use the onConnection and onClose methods for that. But I can't get the headers. So I'm going to have to figure out how else I can know, or when else I can connect, connection id's to users.
