### ISSUE TITLE
HTTP_ONLY cookies included in the html source

### ISSUE THREAD

**Issue by marcodejongh** [gadicc/meteor-headers#42]
Hi @gadicc ,

Thx for the package we used it as inspiration https://github.com/gfk-ba/meteor-server-cookies.

But we actually wanted to use your package so we wouldn't have to keep maintaining ours. However today I found a pretty big security hole in that the meteor-headers script tag inserted into the html also contains http_only cookies. This is a big risk because external scripts could potentially steal session_id's.

**Comment by gadicc** [comment]
Hey @marcodejongh, you're absolutely right of course.   We actually had a filter for `cookie` in general, but it looks like I broke it at some point :(  I've added a test for it now, and better documentation about cookies that get filtered out (in both the History and README files), i.e. document.cookie is available on the client anyways for non httpOnly headers.  Thanks for reporting!
