### ISSUE TITLE
Undocumented requirement, "check"

### ISSUE THREAD

**Issue by rchrd2** [gadicc/meteor-headers#44]
Hello, I installed this and hit an issue where "check" was not defined. I solved this by running `meteor add check`. Maybe this is a super common meteor library, but on a fresh project it was no there.

https://github.com/gadicc/meteor-headers/blob/master/lib/headers-server.js#L36

**Comment by btoueg** [comment]
:+1:

**Comment by gadicc** [comment]
hi guys, sorry for the delay... yeah, meteor 1.2 is a bit stricter; this is fixed now in the 0.0.31 release.
